# .goreleaser.yaml
builds:
- id: kubestellar-syncer
  main: ./cmd/syncer
  binary: kubestellar-syncer
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - s390x
  skip: true

kos:
- build: kubestellar-syncer
  main: ./cmd/syncer
  repository: quay.io/yanagawa_takumi1205/kubestellar-syncer
  tags:
  - '{{.Version}}'
  bare: true
  base_image: cgr.dev/chainguard/static
  preserve_import_paths: false
  sbom: none
  platforms:
  - linux/amd64
  - linux/arm64
  - linux/s390x
