# .goreleaser.yaml
builds:
- id: kubestellar-syncer
  main: ./cmd/syncer
  binary: kubestellar-syncer
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - s390x
kos:
- build: kubestellar-syncer
  main: ./cmd/syncer
  repository: quay.io/yanagawa_takumi1205/kubestellar-syncer
  tags:
  - '{{.Version}}'
  - latest
  bare: true
  preserve_import_paths: false
  platforms:
  - linux/amd64
  - linux/arm64
  - linux/s390x
