name: Add issues to project

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  contents: write
  
jobs:
  create-update-project:
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - uses: actions/checkout@v4.1.0
        with:
          token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          persist-credentials: 'false'
      
      - uses: actions/add-to-project@v0.5.0 # This adds the issue to the project
        with:
          project-url: https://github.com/orgs/kubestellar/projects/2
          github-token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
        id: add-project
      
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/kubestellar/projects/2
          github-token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Status,Date Posted
          field-values: New,${{ steps.date.outputs.date }}
