name: docs-ecutable - Mailbox
run-name: docs-ecutable - Mailbox - ${{ github.ref_name }}

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md"
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-mailbox.yml"
      - "docs/scripts/docs-ecutable.sh"
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md"
      - "docs/content/Coding Milestones/PoC2023q1/mailbox-controller-subs/**"
      - "docs/content/Coding Milestones/PoC2023q1/common-subs/**"
      - ".github/workflows/docs-ecutable-mailbox.yml"
      - "docs/scripts/docs-ecutable.sh"

env:
  docs-ecutable-filename: mailbox
  docs-ecutable-md-filename: "'docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md'"

jobs:
  docs-ecutable:
    name: docs-ecutable - for mailbox e2e
    runs-on: ubuntu-latest
    outputs:
      docs-ecutable-filename: ${{ steps.step1.outputs.docs-ecutable-filename }}
    steps:
      - id: step1
        run: echo "docs-ecutable-filename=${{ env.docs-ecutable-filename }}" >> "$GITHUB_OUTPUT"

      - run: echo ${{ steps.step1.outputs.docs-ecutable-filename }}

      - uses: actions/checkout@v3.6.0
      
      - uses: actions/setup-go@v4
        with:
          go-version: v1.19
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
  
      - run: |
          make MANIFEST="${{ env.docs-ecutable-md-filename }}" \
          docs-ecutable
